### ISSUE TITLE
Suggestion: Loading an external file - error: Custom(ssl@ssl_recv)

### ISSUE THREAD

**Issue by ghost** [HaxeFoundation/code-cookbook#103]
Sources:
* https://code.haxe.org/category/beginner/loading-external-files.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Beginner/loading-external-files.md

**Comment by trsBasicLine10** [comment]
why cant i get the to work..
the error i get is
Main.hx:23: error: Custom(ssl@ssl_recv)

**Comment by trsBasicLine10** [comment]
why cant i get the to work..
the error i get is
Main.hx:23: error: Custom(ssl@ssl_recv)

**Comment by markknol** [comment]
Hi there, what did you try to run it?

**Comment by trsBasicLine10** [comment]
I tried to run the code below from the page
(https://code.haxe.org/category/beginner/loading-external-files.html)
and keep getting the error below the dashed line.
google didn't help me either.



var http = new haxe.Http("https://api.ipify.org?format=json");

http.onData = function (data:String) {
  var result = haxe.Json.parse(data);
  trace('Your IP-address: ${result.ip}');
}

http.onError = function (error) {
  trace('error: $error');
}

http.request();

----------------------------------------
Main.hx:23: error: Custom(ssl@ssl_recv)

**Comment by andyli** [comment]
Looks like you're using an old version of neko. Check that you have neko 2.1.0 or up by `neko -version`. Also it is possible that there are old versions of libneko in PATH.

**Comment by trsBasicLine10** [comment]
neko version is 2.1.0

I had 1 version in path and another in hxcpp subfolder from compiling
hxcpp, both retern 2.1.0

**Comment by 0xA3** [comment]
I had the same problem. Uninstalling Haxe and Neko and then reinstalling solved it for me.

**Comment by Simn** [comment]
Looks like this was some sort of installation problem.
