### ISSUE TITLE
Suggestion: Loading an external file - fails with quotes

### ISSUE THREAD

**Issue by trsBasicLine10** [HaxeFoundation/code-cookbook#104]
```haxe
var http = new haxe.Http("https://api.ipify.org?format=json");
http.onData = function (data:String) {
var result = haxe.Json.parse(data);
trace('Your IP-address: ${result.ip}');
}

http.onError = function (error) {
trace('error: $error');
}
http.request();
```
the above does not work. it throws an error in the most current haxe (2.4.6)

the code below does work. change the " changed to ' 
now it works and gives the jsonified ip address 
I have NO idea what changeing the " to ' made it work.

```haxe
var http = new haxe.Http('http://api.ipify.org?format=json);    
http.onData = function (data:String) {   
var result = haxe.Json.parse(data);  
trace('Your IP-address: ${result.ip}');  
}  
http.onError = function (error) {  
trace('error: $error');  
}  
http.request();  
```

Sources:
* https://code.haxe.org/category/beginner/loading-external-files.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Beginner/loading-external-files.md

**Comment by markknol** [comment]
On which target did this fail?

**Comment by markknol** [comment]
The difference is http/https
