### ISSUE TITLE
Auto deploy to Github Pages

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/code-cookbook#13]
It would be awesome if we can auto deploy this website on Github Pages. Nicolas was ok with this, he will link code.haxe.org to it.

@andyli can you help with this? What do we need?

**Comment by markknol** [comment]
I manually pushed the output here http://haxefoundation.github.io/code-cookbook/

**Comment by nadako** [comment]
You can look at hxnodejs scripts:

https://github.com/HaxeFoundation/hxnodejs/blob/master/.travis.yml
https://github.com/HaxeFoundation/hxnodejs/blob/master/doc-deploy.sh

I think I used this post to do that: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

I can maybe look into this, but not right now, so if someone has free time for that, it should be fairly easy.

**Comment by nadako** [comment]
Works!

**Comment by markknol** [comment]
You are an hero!
