### ISSUE TITLE
Site looks terrible if accessed via https

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/code-cookbook#14]
Try opening https://haxefoundation.github.io/code-cookbook/index.html in chrome and behold.

```
Mixed Content: The page at 'https://haxefoundation.github.io/code-cookbook/index.html' was loaded over HTTPS, but requested an insecure script 'http://haxe.org/js/bootstrap.min.js'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by markknol** [comment]
Ah maybe we should not use https since haxe.org doesnt have it too and I link to some resources of it.

**Comment by markknol** [comment]
Otherwise I include them all in the build.

**Comment by markknol** [comment]
Until we don't have https this is not an issue.
