### ISSUE TITLE
Matching on Structures: example not correct

### ISSUE THREAD

**Issue by manuelcaeiro** [HaxeFoundation/code-cookbook#144]
Table of contents -> Beginner -> Pattern matching -> Matching on structures:

> If we would like to trace the age of the person in the first case we could have written 
> `case { age: age > 50 => true}: trace('found somebody older than 50, the age is $age')`.

does not evaluate as expected.

To get the expected result it should be written something like:

> `case {age: age} if (age > 50): trace('found somebody older than 50, the age is $age.');`

**Comment by markknol** [comment]
Good one, could you do a pullrequest for this?

**Comment by manuelcaeiro** [comment]
Okay, I'll try. Must warn you that I've never done it before, and you know what they say.

**Comment by manuelcaeiro** [comment]
Help me here before I close this, please. This was all new for me.
Now that I'm thinking: I should have made the changes on my local, push it to my fork and... make a push request to your master?

**Comment by Aurel300** [comment]
@manuelcaeiro What you did seems correct. A PR works like this:

 - you make a fork (on GitHub) of the project
 - you checkout your repo on your machine, create a branch for the PR (and that PR only)
 - you make the changes in that new branch
 - you push the commits (they go to your fork)
 - on GitHub, you make a PR from your fork's branch to the original repo
 - somebody approves it or comments, in which case go back to making changes)
 - (you delete the branch, all is done)

**Comment by markknol** [comment]
Or do it the simple way:

- Navigate to https://code.haxe.org/category/beginner/pattern-matching.html
- Press the edit button on any page
![image](https://user-images.githubusercontent.com/576184/78226228-b1e55000-74cb-11ea-9b12-69fbdbded3a7.png)
- Make the change in the online editor
- Set the description / what you changed and press Request change
![image](https://user-images.githubusercontent.com/576184/78226584-3506a600-74cc-11ea-878f-4070ca04107d.png)
- A pull request will be created
