### ISSUE TITLE
Regex literal seems to mess up highlighting

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/code-cookbook#21]
Everything after the regex literal here is just red:

http://code.haxe.org/category/macros/completion-from-url.html

![](http://i.imgur.com/LT74rw0.png)

**Comment by markknol** [comment]
I used a regexp and now I have two problems :confused:  

I might wanna look into different syntax highlighter.

**Comment by markknol** [comment]
done https://github.com/HaxeFoundation/code-cookbook/commit/dedc1af4a75106e2a2a73b6a60d0a1495dc483ad
