### ISSUE TITLE
Library/Toolkit Connect and Commuity Log

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/code-cookbook#23]
Hi would like to propose one or two additional sections.
"Library/Toolkit Connect"
This will eventually include forums on specific haxe targets if they are formed such as Java, NodeJS, c# etc..., but currently should include "active" groups, a good starter might be these.

Luxe
https://gitter.im/snowkit/public ( there is also a Luxe one but I think this is used more )
Kha
irc://ktxsoftware.com/kha
Openfl
http://community.openfl.org/
Flambe
https://groups.google.com/forum/#!forum/flambe
NME
https://gitter.im/haxenme/nme
Fixel
http://haxeflixel.com/documentation/community/

... probably some more but I am sure libraries / toolkits can suggest for themselves you just need a starting list, I can imagine Heaps, Nape etc.. should be added if they have ones, the important aspect maybe activity, I think it might be very hard to order these by activity but perhaps that would be ideal, certainly it would help new users know which projects to explore, and would be very relatively fair on projects.

Also it would be ideal to work towards a "Community Log"
Ideally it would be amazing to have a collated log of new posts/topics in some form from the Haxe and library forums, but I don't have any code for this it's just an additional suggestion to the Library Connect proposal, and not one I would be able to implement.

Certainly I can look at creating a pull request for "Library/Toolkit Connect" if such a concept seems interesting to reduce the workload on Mark, but maybe you disagree with my logic which I was originally going to put in a haxelang email but decided to post here.

"It would be really nice to maybe go a bit further with the "Connect" section to cover more specific ecosystems where users share promote and discuss Haxe related projects, it's often more worthwhile hanging out on some of these if you want to discuss more specific topics."

Certainly something along these lines might be useful to clarify the section.

All looks good best Justin. :)

**Comment by Simn** [comment]
code.haxe.org is focused on code examples and tutorials, not the Haxe community as a whole. I don't think we should conflate that either. We could discuss adding a "Communities" page under the connect menu on haxe.org, but that's more of a discussion for the haxe.org or ProjectManagement repository.
