### ISSUE TITLE
Code-style consistency

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/code-cookbook#3]
It didn't take us long to become inconsistent with our indentation:

http://haxe-cookbook.stroep.nl/validate-json.html has two-space tabs.
http://haxe-cookbook.stroep.nl/Null-safety.html has four-space tabs.

**Comment by markknol** [comment]
Maybe I can replace all tabs by spaces while generating the thing. Tabs are pretty useless in html.

**Comment by Simn** [comment]
Yes but even then we have to agree on a width.

**Comment by markknol** [comment]
I would say 2 spaces because that don't use much horizontal space.

**Comment by Simn** [comment]
I'll give you the 2 spaces if you give me braces-on-same-line in return!

**Comment by markknol** [comment]
Ok ok.  OK!

Ill format everything.

**Comment by Simn** [comment]
Alright, thanks!

By the way, where is that object pool example from? It has... various parts that are... questionable? Might be a good candidate for removal.

**Comment by markknol** [comment]
Ok Ill removed it. Also did formatting.

**Comment by Simn** [comment]
Alright, thank you!
