### ISSUE TITLE
Request for "Graphics" section and initial tentative start on colored triangle webgl.

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/code-cookbook#35]
Mark 

Hi I started on improving the webgl triangle example ( just colored triangles yet to tidy up the image one yet ), and have made a start on a tutorial but there is just so much to cover it's tricky to know if I have the patience to try to go into every detail, but it's a start, but I suggest that Codebook has a Intermediate "Graphics" section where I could also add swing, svg, canvas, flash, kha, flambe, flump examples of triangle drawing, rendering an image etc..

https://github.com/Justinfront/CookbookGraphics/blob/master/cookbookGraphics/triangleHaxeLogo/webgl/tutorial/webgl_triangleHaxeLogo.md

I don't know it this quite fits with your vision please let me know if this is useful and worth integration of some form, also maybe if it is then it would be good to continue it separately before forming a pull ?

Best Justin

**Comment by markknol** [comment]
This is nice! 

Some tips when you are moving it into the book:

* Call the page "webgl_triangles.md"

* You can create a new category called "Intermediate" in [this directory](https://github.com/HaxeFoundation/code-cookbook/tree/master/assets/content/cookbook).

* You can add the demo/assets/images in a new folder called "demos/webgl_triangles/" in [this directory](https://github.com/HaxeFoundation/code-cookbook/tree/master/assets/includes)
Then you can include the actual demo like this `<iframe src="/demos/webgl_triangles/demo1.html"></iframe>`

*  "WebGL" and "JavaScript"

**Comment by Justinfront** [comment]
Not sure how to test the iframe locally as the instructions reference a bat?  Also wondering if it might be feasible to setup so that the webgl_triangles.md just loaded from another repository on the fly.

**Comment by markknol** [comment]
The bat file cleans the output folder. But basically it does `neko CodeCookBook.n` this generates the html pages which is needed for local testing. 

Not sure if I understand what youre asking but I dont think linking to external repositories is something I want, lets keep it simple and all in one place.

**Comment by Justinfront** [comment]
I have created another example based on this code and the code in draw2triangle.
https://rawgit.com/Justinfront/CookbookGraphics/master/cookbookGraphics/imageHaxeLogo/webgl/index.html
It needs a tiny bit more work as the shader has some hard coded values in, have yet to write up this demo, it uses inline Haxe Logo gif.  But should cover the shader step function as a trick to avoid 'if'.
It's fairly similar structure so will only need to document the differences.

**Comment by markknol** [comment]
When can I expect this section?

**Comment by markknol** [comment]
I close this issue for now since nothing is really happening. If you have any questions let me know. I hope to put the content you've created so far in the cookbook some day. Take care!

**Comment by nanjizal** [comment]
I believe that github is now empty, he mentioned new corporate ip restrictions at work, and an ill family member, no doubt he will contribute when he can.
