### ISSUE TITLE
Macro example, [Add property with getter], import inside class

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/code-cookbook#48]
Are you allowed to have import inside a class definition, or was that a copy/paste error? I got a compiler error, Unexpected import, using Haxe 3.3.0.

![image](https://cloud.githubusercontent.com/assets/2192439/16119887/c70c1bc4-339a-11e6-8f9b-b85cc9e3b708.png)

Sources:
* http://code.haxe.org/category/macros/build-property-with-inline-getter.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Macros/build-property-with-inline-getter.md

**Comment by markknol** [comment]
Thank you for the wonderful bug report, so nicely formatted :smile: 

I fixed it, it was a copy/paste error I guess.
