### ISSUE TITLE
Code example max width?

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/code-cookbook#5]
Do we want to set a max width for our code examples? It would be nice to have them properly formatted on an average landscape cellphone screen, but I'm not sure if we would have to make too many concessions for this.

**Comment by markknol** [comment]
This is covered in the readme

> judicious use of extra line-breaks to avoid ugly automatic breaks (check the output)

**Comment by Simn** [comment]
Yes but I was thinking that there might be a magic number which makes it look good on 99% of the screens or something.
