### ISSUE TITLE
Increase code readability

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/code-cookbook#51]
In my opinion the code is a bit hard to read. I think it is a combination of the font and a somewhat small font size. 

Here's a concrete example from the Cookbook where the text is big and clear but the code is lacking in clarity.

> ![screen shot 2016-08-16 at 09 10 57](https://cloud.githubusercontent.com/assets/879967/17690828/6e36232e-6391-11e6-8e3b-82bc346aaa51.png)

---

Here's an _example_ where I've tried substituting the code font with another. I've used the [Inconsolata](https://fonts.google.com/specimen/Inconsolata?selection.family=Inconsolata) font with a size of 15px.

> ![screen shot 2016-08-16 at 09 44 07](https://cloud.githubusercontent.com/assets/879967/17691637/07525880-6396-11e6-9472-b174c52430a4.png)

In my opinion this makes for clearer code and aligns better with the text.

**Comment by markknol** [comment]
We use the same code font on all Haxe sub sites, so if this is going to be changed I want to change it everywhere. The Inconsolata font requires custom webfonts, which increases the load time a bit. That's not a big issue but now we have a monospaced font for "free".

I did some quick googling:  
* Google uses Roboto Mono 15px for their docs [example](https://developers.google.com/custom-search/docs/structured_data)
* Mozilla uses consolas (same as us), but 14px [example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)
* MSDN uses consolas (same as us), but 13px [example](https://msdn.microsoft.com/en-us/library/ms165392.aspx)

The easiest thing, maybe, it to just increase the font size. However, I do like the Roboto Mono, even more than Inconsolata, but that may be a preference. Ill do some tests with it.

Btw, which OS/browser do you use? The aliassing looks very "fat" compared to what I see.

**Comment by anissen** [comment]
Thanks for your reply! 👍 

> We use the same code font on all Haxe sub sites, so if this is going to be changed I want to change it everywhere.

Ahh I see. Not as small a change as I've thought then. On the other hand, it's an opportunity to improve all the Haxe sub-sites ;)

> The easiest thing, maybe, it to just increase the font size. However, I do like the Roboto Mono, even more than Inconsolata, but that may be a preference. Ill do some tests with it.

I agree on both counts. Increasing the font size seems to do a lot for readability but I also prefer Roboto Mono over the Consolas.

> Btw, which OS/browser do you use?

I'm on OS X 10.11 and using Chrome 52. Here's an a comparison screenshot (Chrome at the top, Safari at the bottom):
![screen shot 2016-08-16 at 19 46 15](https://cloud.githubusercontent.com/assets/879967/17709657/5b3590b2-63ea-11e6-8cd9-c8e5ee5990e6.png)
