### ISSUE TITLE
Improve Google discoverability

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/code-cookbook#52]
For some reason, code.haxe.org doesn't seem to rank very highly on google.. googling for `static extensions haxe`, I get the Haxe Manual's article as the first result:

https://haxe.org/manual/lf-static-extension.html

The code cookbook snippet for static extensions doesn't show up anywhere though (at least not in the first five pages):

http://code.haxe.org/category/beginner/using-static-extensions.html

This is a bit of a shame, especially because a lot of people seem to struggle with the manual's technical wording - the cookbook has more of a tutorial-style that is beginner-friendly.

Linking to code cookbook snippets from the Haxe Manual might help. Perhaps some things could also be linked to from the API docs? Not static extensions of course, there's no API for that, but maybe macros.

**Comment by markknol** [comment]
Yes, this is a very important thing I also noticed.

For now, I did some changes to the markup and just starting observing using the Google Search Console. Let's see if that brings some improvements.

**Comment by markknol** [comment]
* There are now links in the manual
* The markup + meta descriptions has updated for better SEO
* The static extensions page is now on page 1 on google.

Ill close this issue since I think its good enough for now. The best we can do from this point is adding much more content :smile:
