### ISSUE TITLE
[Conditional compilation]

### ISSUE THREAD

**Issue by BitsAtPlayDev** [HaxeFoundation/code-cookbook#54]
At the bottom of the page, the link next to _"Learn about available global compiler flags here"_

http://haxe.org/manual/lf-condition-compilation-flags.html

is broken.

I think the correct link is:

http://haxe.org/manual/compiler-usage-flags.html

Sources:
* http://code.haxe.org/category/beginner/conditional-compilation.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Beginner/conditional-compilation.md

**Comment by markknol** [comment]
Thanks for reporting! Enjoy your day!

**Comment by BitsAtPlayDev** [comment]
oops! The wrong link was changed ...

This link _**was**_ correct, now it goes to wrong page --> _Learn about conditional compilation here: https://haxe.org/manual/compiler-usage-flags.html_

This is the link that was, and is, still broken --> _Learn about available global compiler flags here: https://haxe.org/manual/lf-condition-compilation-flags.html_

Sorry for confusion :)

**Comment by markknol** [comment]
Oops my fault :open_mouth: It is correct now!
