### ISSUE TITLE
Make it possible to group entries if they are part of a series

### ISSUE THREAD

**Issue by dstrekelj** [HaxeFoundation/code-cookbook#59]
Currently, the cookbook is designed to accommodate single entries grouped by tags and categories. This is great for code snippets and small examples.

However, there is no way to effectively group together a _series of entries_, for instance, that concern the development of a (larger) project. Displaying every series entry in the sidebar would quickly inflate the sidebar and make it hard to navigate.

I would like to discuss the possibility of supporting a system for series. I feel like this is a necessity if bigger examples are to be hosted by the cookbook, such as those that were present in the old Haxe documentation.

Here is a proposal to start things off:
* Series of examples are placed in their own category (e.g. "Series")
* A series has a landing page, which will be accessible from the sidebar
  * The landing page briefly describes the series - its topic, motivation, and proposed solution
  * It serves as both the series' introduction and table of contents
* Every entry contains links to other entries, including the landing page
  * Note that this would not mean the behaviour of a series page imitates a single-page application

The folder structure might look something like this:

```
cookbook
+- ...
`- Series
  `- my-cool-series
    +- my-cool-series.md
    +- my-cool-series-1-set-up.md
    +- my-cool-series-2-tear-down.md
    `- my-cool-series-3-conclusion.md
```

I'm interested in hearing your thoughts on the matter!

**Comment by markknol** [comment]
I think this is a good idea. I'm going to look for ways to support this. In the meanwhile you can already start a serie somewhere :wink:
