### ISSUE TITLE
Categories / Organisation

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/code-cookbook#7]
How do we want to structure all snippets, which categories do we need?

**Comment by cambiata** [comment]
Added "Abstract types" as a category a minute ago, together with an Email type example.

**Comment by Jon2211** [comment]
Hello - I would like to join this project and help out writing examples.  Is there a roadmap of snippets that needed to be written?  Thinking of what tripped me up were how Value worked - esp. the ._ acccess.  Other beginner stuff I could add - declaring variables, setters, getters.

**Comment by markknol** [comment]
Hi! Great you want to help. No there is not a roadmap, but the goal is to create a practical guide to people into Haxe. I find people on the forum or stackoverflow struggle with how-to-do stuff. Thats one of the reasons of this cookbook.
My goal is to filter relevant questions and make snippets out of that. So if youre looking for inspiration check what people are searching dor yourself too.
 For example, many think macros are extreme hard or magical. This thought exist because there isnt much known or written about it. I hope to have a decent amount of macro samples to erase that thought and demonstrate the power. 

For the beginner section I think we want to write about arrays, core types, lambdas, regular expressions, json, xml, enums/adt, typedefs, math, conditional compilation, pattern matching, etc etc. Haha all the great stuff!

**Comment by Jon2211** [comment]
ok - thanks - I put an entry in about variables earlier that got some feedback- so I'll just keep plugging away at that- then maybe I'll start on some of the things above (arrays, base types etc)

**Comment by cambiata** [comment]
Maybe there should be a separate category called "Compiling"?

I will create a PR for a recepie called "Compiling libraries without main class" - that one could fit there.
Also, the "Conditional compilation" could be moved there.
Coming explanations/details about of different compiler targets, compiler flags etc could fit there...

What do you think?

**Comment by markknol** [comment]
I rather call it "compilation"

**Comment by markknol** [comment]
I am starting to feel uncorfortable with the "other" category, should we create new ones?

**Comment by cambiata** [comment]
Yes. Maybe "Data structures" for the iterator and arrays stuff...?

Sooner or later, there will be a need for differentiation on targets. This might however lead to the need for subcategories... Javascript is very hot these days, and it has its own paradigms and workflows, so it should be easy to find the js stuff!
Categories>Subcategories - what do you think?

**Comment by dstrekelj** [comment]
I agree that the 'Other' category should be split into numerous different ones. It's kind of difficult to determine what sort of categories would be suitable candidates, really.

Target-specific categories seem like a step in the right direction. It would be nice to provide cookbook readers with an introduction to writing code for supported languages. This something that comes up every so often on IRC and should be addressed.

People also tend to ask about data structures: if hash tables exist in Haxe, or how someone can use a structure as a key in a map if Haxe passes them by reference instead of value. A couple of recipes in this category would clean up any misconceptions fairly quickly.

**Comment by MatthijsKamstra** [comment]
https://github.com/cambiata/code-cookbook-ideas/wiki

https://github.com/cambiata/code-cookbook-ideas/issues/1#issuecomment-283190127

**Comment by markknol** [comment]
I think we indeed need a category for the top most popular libraries in the cookbook, with introduction and getting started code and outlinks links to their website. But the rest is up to the libraries itself. As for the target specific articles, Ill wait for the people to bring them in 😄 

For now Ill close this topic, as there is nothing more to discuss. Please keep contributing 👍
