### ISSUE TITLE
[Add parameters as fields] compile error

### ISSUE THREAD

**Issue by ustutz** [HaxeFoundation/code-cookbook#75]
Sources:
* http://code.haxe.org/category/macros/add-parameters-as-fields.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Macros/add-parameters-as-fields.md

When compiling the example there is an error
src/MyMacro.hx:19: characters 10-23 : Array<haxe.macro.ClassField> has no field exists

I created a corrected version
https://github.com/ustutz/init_locals_macro

**Comment by Simn** [comment]
The `exists` comes from `using Lambda`, which works fine for me.

**Comment by ustutz** [comment]
Sorry, I missed the Lambda line.
Thanks :-)
