### ISSUE TITLE
[Email address as abstract type]

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/code-cookbook#79]
I came across the example using ereg for email validation. It uses a way too restrictive regex for validation, which users will copy and paste. I suggest simplifying it, [something like ~/.+@.+\\..+/i](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/).

Sources:
* http://code.haxe.org/category/abstract-types/emailaddress.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Abstract types/EmailAddress.md

**Comment by Simn** [comment]
Yeah I never understood why people make such a science out of validating email addresses via regex.

**Comment by markknol** [comment]
Hi Ben, thanks! this is a good suggestion, can you update the snippet and create a pull request for it?
