### ISSUE TITLE
[Add git commit-hash in build ]

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/code-cookbook#8]
I think in a macro like this we should also show usage of `#if display`, so macro won't call `git` for completion.

Sources:
* http://haxe-cookbook.stroep.nl/add-git-commit-hash-in-build.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/assets/content//cookbook/Macros/add-git-commit-hash-in-build.md

**Comment by markknol** [comment]
What a lovely formatted issue. Please PR :wink:

**Comment by nadako** [comment]
Sorry, I didn't have time to PR yet, thanks for updating it!
