### ISSUE TITLE
[Working with compiler flags] Broken link

### ISSUE THREAD

**Issue by gogoprog** [HaxeFoundation/code-cookbook#85]
The link in the last sentence is broken :

> Learn about available global compiler flags here: https://haxe.org/manual/lf-condition-compilation-flags.html

Sources:
* http://code.haxe.org/category/macros/get-compiler-define-value.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Macros/get-compiler-define-value.md

**Comment by markknol** [comment]
Thanks foe reporting! https://github.com/HaxeFoundation/code-cookbook/commit/25d0df509b54c5f8306615b3129efb5e446d6736
