### ISSUE TITLE
"Observer" design pattern article doesn't credit author

### ISSUE THREAD

**Issue by matrefeytontias** [HaxeFoundation/code-cookbook#97]
I wrote this article, which was merged some time ago after edits by @markknol , but I just realize now that [the online article](https://code.haxe.org/category/design-patterns/observer.html) doesn't credit me at all. I believe it should list me as author, or at least contributor.

**Comment by markknol** [comment]
Ah, good one. For some reason sometimes isn't picked up. Good news is you can 'claim' being the author, by just mentioning it in the article, like this.

```markdown
> Author: [matrefeytontias](https://github.com/matrefeytontias)
```
