### ISSUE TITLE
Observer - doesn't seem to work with --interp

### ISSUE THREAD

**Issue by cambiata** [HaxeFoundation/code-cookbook#98]
Sources:
* https://code.haxe.org/category/design-patterns/observer.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Design-patterns/observer.md

Hi Mark!
This example doesn't seem to work with --interp - the observable is never registered. 
Works with ordinary neko though. Strange...

/ Jonas

**Comment by markknol** [comment]
Which Haxe version are you using?
And what exactly does it trace? 

cc @nadako @ncannasse @simn

**Comment by cambiata** [comment]
Haxe 4.0.0-preview.1-win

It traces nothing, because the Watched instance isn't found in the observables map.

When adding the following `trace(subject)`...

```
  static public function notify(subject:{}, ?data:Any)
  {
    trace(subject); // <-   
    if(observables.exists(subject))
      for(obs in observables[subject])
        obs.notified(subject, data);
  }
```
... on node and neko it outputs
`> { __id__ => 0, number => 3 } `
or something like that, but on --interp it outputs 
`> Watched`

So, when running --interp it seemes like the Watched object is registered not with it's instance, but with it's class name... Or something...

**Comment by markknol** [comment]
Do you mind checking if this is also the case with Haxe 4.0.0-preview.2-win ?

**Comment by cambiata** [comment]
Haxe 4.0.0-preview2-win works fine! :-)

**Comment by markknol** [comment]
I guess thats why they call it a preview :) thanks for checking though!
