### ISSUE TITLE
Suggestion: Adding static methods to existing classes

### ISSUE THREAD

**Issue by trsBasicLine10** [HaxeFoundation/code-cookbook#99]
there is a "zz" that I think should be a "ss". I am new here so I could be wrong.

Sources:
* https://code.haxe.org/category/other/adding-static-methods-to-existing-classes.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Other/adding-static-methods-to-existing-classes.md

@ashes999

**Comment by Gama11** [comment]
`class` is a keyword. Using `clazz` instead is a common workaround.

**Comment by trsBasicLine10** [comment]
I was guessing it might be intentional  but couldn't figure it out. Good to
know. Thanks.

**Comment by markknol** [comment]
Maybe we should rename it to `cl`.
